# Generated by Django 5.2.5 on 2025-08-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_URL',
            field=models.URLField(blank=True, help_text='URL to the movie poster image.'),
        ),
    ]
