# Generated by Django 5.2.5 on 2025-08-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_movie_poster_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, help_text='The genre of the movie.', max_length=50),
        ),
    ]
