# Generated by Django 5.2.5 on 2025-08-18 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_movie_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='is_reserved',
        ),
        migrations.AddField(
            model_name='function',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The price of the ticket for the function.', max_digits=6),
        ),
    ]
