# Generated by Django 5.2.5 on 2025-08-23 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_remove_seat_is_reserved_function_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='movie_name',
        ),
    ]
